version: "3.4"
services:
   postgres:
      container_name: threads-db
      image: postgres
      ports:
         - "5432:5432" # Added a space and enclosed in quotes
      volumes:
         - postgres_data:/var/lib/postgresql/data # Removed the dash in front of the volume name
      environment:
         # Corrected spelling
         POSTGRES_USER: postgres
         POSTGRES_DB: threads
         POSTGRES_PASSWORD: threads

volumes:
   postgres_data:
